category: "crypto"
name:     "Перевёртыш"
points:   100
author:   kalan
description: |
    <p>Наташ, вставай, мы там всё перевернули. Вообще всё.
generator: generate.py
submit_not_after: "2020-06-06T12:00:00Z"
